refactor!: use vim.api.nvim_set_hl()
andersevenrud/nordic.nvim pull request #70
Opened 2022-02-01 21:51 UTC by gegoune

Completely broken.

2022-02-01 21:53 UTC, gegoune commented
Not sure why it's never going into `table` conditional in https://github.com/andersevenrud/nordic.nvim/pull/70/files#diff-87af52ac4b5511b195aa96dd5bdea0128de6210195d900717f6e55f58c004c66R111. 

I am trying to make output from nordic functions to return objects that are ready to be injected into `vim.api.nvim_set_hl()`.

2022-02-01 21:59 UTC, andersevenrud requested changes
There's no need to touch the abstraction here. You can simply replace:

```
                vim.highlight.create(group[1], {
                    guifg = group[2] or 'NONE',
                    guibg = group[3] or 'NONE',
                    gui = group[4] or 'NONE',
                    guisp = group[5] or 'NONE',
                })
```

with:

```
                vim.api.nvim_set_hl(0, group[1], {
                    guifg = group[2] or 'NONE',
                    guibg = group[3] or 'NONE',
                    gui = group[4] or 'NONE',
                    guisp = group[5] or 'NONE',
                })

```

2022-02-01 22:00 UTC, andersevenrud commented
Ignore that comment. I clearly misread something in the docs. Stand by...

2022-02-01 22:18 UTC, andersevenrud commented
Well, not that far off :sweat_smile: I was unaware of the naming and that the `gui` attribute is now split into properties.

```lua
                local definition = {
                    fg = group[2] or 'NONE',
                    bg = group[3] or 'NONE',
                    sp = group[5] or 'NONE',
                }

                if group[4] then
                    definition[group[4]] = true
                end

                vim.api.nvim_set_hl(0, group[1], definition)

```

One thing I don't know about here is `underline` though, because that's an option, and I don't know if `underline` supports a non-bool value :man_shrugging: I can't find the definition of this in the docs for some reason...

2022-02-01 22:21 UTC, gegoune commented
Thanks! Will look into it tomorrow. But basically you are against changing group configurations the way I did in fidget.lua or standard.lua? Should make it easier for that very PR, but could get rid of those `table[n]` maps.

Thanks for looking into it!

2022-02-01 22:26 UTC, andersevenrud commented
> But basically you are against changing group configurations

Nope.

I just didn't understand the impact of using this function.

But now that I get it this should be fairly easy to do. The fastest way is to change the tables from this:

```
{ name | table, fg, bg, style, sp }
```

to:

```
{ name | table, { fg = '', bg = '' } }
```

Then finally:

```lua
    local function load_group(list)
        for _, group in ipairs(list) do
            if type(group) == 'function' then
                load_group(group(unpack(arguments)))
            elseif type(group[1]) == 'table' then
                load_group(vim.tbl_map(function(highlight)
                    return { highlight, group[2] }
                end, group[1]))
            else
                vim.api.nvim_set_hl(0, group[1], group[2])
            end
        end
    end
```

2022-02-01 22:38 UTC, andersevenrud commented
FYI: I updated the description with some tasks

2022-02-01 22:52 UTC, andersevenrud requested changes
I believe the changes in the following reference is the best way to solve this considering the internal API for color definitions supports tables as names.

https://github.com/andersevenrud/nordic.nvim/pull/70#issuecomment-1027349291

Basically, keep things as is, but put the stylings into a separate nested table instead of a completely flat table.

2022-02-01 22:59 UTC, andersevenrud commented
There's actually an even simpler way for this, but I'm not sure how I feel about it because it involves using some black Lua magic to have a mix between a list and an associative array:

```lua
-- This works :o
local t = { "foo", fg = "bar" }
print(t[0])
print(t.fg)
```

Which means that technically one can do this:

```
{ name | name[], fg = '', bg = '', ... }
```

```lua
        for _, group in ipairs(list) do
            if type(group) == 'function' then
                load_group(group(unpack(arguments)))
            elseif type(group[1]) == 'table' then
                load_group(vim.tbl_map(function(highlight)
                    return { highlight, group }
                end, group[1]))
            else
                local definition = {}
                for k, v in pairs(group) do
                  if type(k) == 'string' then
                    definition[k] = v
                  end
                done
                vim.highlight.create(group[1], definition)
            end
        end
```

2022-02-03 22:55 UTC, gegoune commented
I will come back to it, but most likely not in next couple of weeks unfortunately.

2022-02-03 23:01 UTC, andersevenrud commented
Alright. Take your time :)

2025-12-02 15:48 UTC, closed without merging